### ISSUE TITLE
origin of the code

### ISSUE THREAD

**Issue by DJCrashdummy** [nextcloud/nextcloud-filelink#2]
_sorry for posting this as an issue... but i don't know where else to get easily in touch with the right recipient(s)._

i saw you modified the code from the old ownCloud-addon (https://addons.mozilla.org/thunderbird/addon/owncloud-for-filelink/), but why you didn't take the still working addon (https://addons.mozilla.org/thunderbird/addon/smart-owncloud-filelink/)?

thanks for enlightenment and if you don't noticed it, maybe i gave a useful hint...

**Comment by oparoz** [comment]
The original code is actually located here:
https://github.com/kewisch/filelink-webdav
which itself is based on a reference implementation posted by Mozilla.

Since I only intend on supporting Nextcloud, it didn't make sense to patch the version found in the ownCloud domain.

I have no idea where the "smart" version is hosted, so I didn't take a look at it.
